services:
  backend:
    container_name: backend
    image: maxorel/backend-compose-optimized:1.0.0
    ports:
      - "${BACKEND_PORT:-4000}:3000"
    env_file: .env
    restart: always
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: maxorel/frontend-compose-optimized:1.0.1
    restart: always
    ports:
      - "${FRONTEND_PORT:-9000}:80"
    env_file: .env

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres

  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT:-9001}:8080"
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:
