services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-compose
    ports:
      - "4000:3000"
    env_file: .env

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-compose
    ports:
      - "9000:3000"
    env_file: .env

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env

  adminer:
    image: adminer
    ports:
      - 9001:8080
